#!/usr/bin/env python3
"""Convert SmartGift catalog JSON into MySQL DDL + product_prices seed."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def sql_str(value: object | None) -> str:
    if value is None:
        return "NULL"
    text = str(value)
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def sql_num(value: object | None) -> str:
    if value is None or value == "":
        return "NULL"
    return str(value)


def sql_int(value: object | None) -> str:
    if value is None or value == "":
        return "NULL"
    return str(int(value))


def sql_json(value: object | None) -> str:
    if value is None:
        return "NULL"
    return sql_str(json.dumps(value, ensure_ascii=False, separators=(",", ":")))


def chunked(rows: list[str], size: int) -> list[list[str]]:
    return [rows[i : i + size] for i in range(0, len(rows), size)]


def emit_inserts(table: str, columns: str, rows: list[str], out: list[str], size: int = 80) -> None:
    if not rows:
        return
    for batch in chunked(rows, size):
        out.append(f"INSERT INTO {table} ({columns}) VALUES")
        out.append(",\n".join(f"  ({row})" for row in batch) + ";")
        out.append("")


def build_sql(data: dict) -> str:
    out: list[str] = []
    meta = data.get("metadata") or {}
    source_pdf = meta.get("source_pdf") or "SmartGift_2026_Portfolio_Blueprint.pdf"

    out.append("-- SmartGift catalog → MySQL product prices")
    out.append(f"-- Source JSON: 1smartgift_catalog_master.json ({source_pdf})")
    out.append("-- Generated by scripts/smartgift-json-to-mysql.py")
    out.append("SET NAMES utf8mb4;")
    out.append("SET FOREIGN_KEY_CHECKS = 0;")
    out.append("")
    out.append("CREATE DATABASE IF NOT EXISTS smartgift")
    out.append("  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    out.append("USE smartgift;")
    out.append("")
    out.append("DROP TABLE IF EXISTS sg_bundle_offers;")
    out.append("DROP TABLE IF EXISTS sg_corporate_bundles;")
    out.append("DROP TABLE IF EXISTS sg_offer_components;")
    out.append("DROP TABLE IF EXISTS sg_aliases;")
    out.append("DROP TABLE IF EXISTS sg_catalog_offers;")
    out.append("DROP TABLE IF EXISTS product_prices;")
    out.append("DROP TABLE IF EXISTS sg_products;")
    out.append("DROP TABLE IF EXISTS sg_categories;")
    out.append("DROP TABLE IF EXISTS sg_sub_catalogs;")
    out.append("")
    out.append("""CREATE TABLE sg_categories (
  slug VARCHAR(64) NOT NULL PRIMARY KEY,
  name_th VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  vibe VARCHAR(255) NULL,
  target_recipient VARCHAR(255) NULL,
  guardrail TEXT NULL,
  core_signatures JSON NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_products (
  code VARCHAR(32) NOT NULL PRIMARY KEY,
  name_th VARCHAR(255) NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  category_slug VARCHAR(64) NOT NULL,
  category_name VARCHAR(255) NULL,
  product_master VARCHAR(64) NULL,
  product_family VARCHAR(64) NULL,
  srp_price DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'THB',
  source VARCHAR(64) NOT NULL DEFAULT 'smartgift_2026',
  KEY idx_sg_products_category (category_slug),
  KEY idx_sg_products_family (product_family)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE product_prices (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(64) NOT NULL,
  item_type ENUM('product','offer','bundle') NOT NULL,
  name VARCHAR(255) NOT NULL,
  category_slug VARCHAR(64) NULL,
  gift_tier VARCHAR(32) NULL,
  min_qty INT NOT NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'THB',
  source VARCHAR(64) NOT NULL DEFAULT 'smartgift_2026',
  UNIQUE KEY uk_product_prices_sku_qty (item_type, sku, min_qty),
  KEY idx_product_prices_sku (sku),
  KEY idx_product_prices_type (item_type, unit_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_catalog_offers (
  offer_code VARCHAR(32) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  gift_tier VARCHAR(32) NULL,
  page INT NULL,
  interest_theme VARCHAR(255) NULL,
  interest_theme_slug VARCHAR(64) NULL,
  supplier_code VARCHAR(32) NULL,
  catalog_match_status VARCHAR(255) NULL,
  unboxing_experience TEXT NULL,
  product_master VARCHAR(64) NULL,
  product_family VARCHAR(64) NULL,
  has_price TINYINT(1) NOT NULL DEFAULT 0,
  price_min DECIMAL(12,2) NULL,
  price_max DECIMAL(12,2) NULL,
  KEY idx_sg_offers_theme (interest_theme_slug),
  KEY idx_sg_offers_tier (gift_tier),
  KEY idx_sg_offers_has_price (has_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_offer_components (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  offer_code VARCHAR(32) NOT NULL,
  product_code VARCHAR(32) NOT NULL,
  qty INT NOT NULL DEFAULT 1,
  UNIQUE KEY uk_sg_offer_component (offer_code, product_code),
  KEY idx_sg_offer_components_product (product_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_aliases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item_type ENUM('product','offer') NOT NULL,
  sku VARCHAR(64) NOT NULL,
  alias VARCHAR(255) NOT NULL,
  UNIQUE KEY uk_sg_alias (item_type, sku, alias(191)),
  KEY idx_sg_aliases_sku (sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_corporate_bundles (
  bundle_code VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  target_recipients INT NULL,
  total_price DECIMAL(12,2) NOT NULL,
  description TEXT NULL,
  landed_cost DECIMAL(12,2) NULL,
  gross_profit DECIMAL(12,2) NULL,
  gross_margin_percent DECIMAL(8,2) NULL,
  meets_min_profit_threshold TINYINT(1) NULL,
  tier_breakdown JSON NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_bundle_offers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bundle_code VARCHAR(64) NOT NULL,
  offer_code VARCHAR(32) NOT NULL,
  qty INT NOT NULL DEFAULT 1,
  UNIQUE KEY uk_sg_bundle_offer (bundle_code, offer_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")
    out.append("""CREATE TABLE sg_sub_catalogs (
  code VARCHAR(64) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
""")

    category_rows = []
    for cat in data.get("top_level_categories") or []:
        category_rows.append(
            ", ".join(
                [
                    sql_str(cat.get("slug")),
                    sql_str(cat.get("name_th")),
                    sql_str(cat.get("name_en")),
                    sql_str(cat.get("vibe")),
                    sql_str(cat.get("target_recipient")),
                    sql_str(cat.get("guardrail")),
                    sql_json(cat.get("core_signatures")),
                ]
            )
        )
    emit_inserts(
        "sg_categories",
        "slug, name_th, name_en, vibe, target_recipient, guardrail, core_signatures",
        category_rows,
        out,
    )

    product_rows = []
    price_rows = []
    alias_rows = []
    for product in data.get("canonical_products") or []:
        code = product.get("code")
        name = product.get("name_th") or product.get("name_en")
        product_rows.append(
            ", ".join(
                [
                    sql_str(code),
                    sql_str(product.get("name_th")),
                    sql_str(product.get("name_en")),
                    sql_str(product.get("category_slug")),
                    sql_str(product.get("category")),
                    sql_str(product.get("product_master")),
                    sql_str(product.get("product_family")),
                    sql_num(product.get("srp_price")),
                    "'THB'",
                    sql_str("smartgift_2026"),
                ]
            )
        )
        for tier in product.get("price_tiers") or []:
            price_rows.append(
                ", ".join(
                    [
                        sql_str(code),
                        "'product'",
                        sql_str(name),
                        sql_str(product.get("category_slug")),
                        "NULL",
                        sql_int(tier.get("min_qty")),
                        sql_num(tier.get("unit_price")),
                        "'THB'",
                        sql_str("smartgift_2026"),
                    ]
                )
            )
        seen_aliases = set()
        for alias in product.get("aliases") or []:
            alias_text = str(alias).strip()
            if not alias_text or alias_text in seen_aliases:
                continue
            seen_aliases.add(alias_text)
            alias_rows.append(
                ", ".join(["'product'", sql_str(code), sql_str(alias_text)])
            )

    emit_inserts(
        "sg_products",
        "code, name_th, name_en, category_slug, category_name, product_master, product_family, srp_price, currency, source",
        product_rows,
        out,
    )

    offer_rows = []
    component_rows = []
    for offer in data.get("catalog_offers") or []:
        code = offer.get("offer_code")
        name = offer.get("name")
        tiers = offer.get("price_tiers") or []
        prices = [float(t["unit_price"]) for t in tiers if t.get("unit_price") is not None]
        has_price = 1 if prices else 0
        offer_rows.append(
            ", ".join(
                [
                    sql_str(code),
                    sql_str(name),
                    sql_str(offer.get("gift_tier")),
                    sql_int(offer.get("page")),
                    sql_str(offer.get("interest_theme")),
                    sql_str(offer.get("interest_theme_slug")),
                    sql_str(offer.get("supplier_code")),
                    sql_str(offer.get("catalog_match_status")),
                    sql_str(offer.get("unboxing_experience")),
                    sql_str(offer.get("product_master")),
                    sql_str(offer.get("product_family")),
                    str(has_price),
                    sql_num(min(prices) if prices else None),
                    sql_num(max(prices) if prices else None),
                ]
            )
        )
        for tier in tiers:
            price_rows.append(
                ", ".join(
                    [
                        sql_str(code),
                        "'offer'",
                        sql_str(name),
                        sql_str(offer.get("interest_theme_slug")),
                        sql_str(offer.get("gift_tier")),
                        sql_int(tier.get("min_qty")),
                        sql_num(tier.get("unit_price")),
                        "'THB'",
                        sql_str("smartgift_2026"),
                    ]
                )
            )
        seen_comp = set()
        for component in offer.get("components") or []:
            product_code = component.get("product_code")
            key = (code, product_code)
            if key in seen_comp:
                continue
            seen_comp.add(key)
            component_rows.append(
                ", ".join(
                    [
                        sql_str(code),
                        sql_str(product_code),
                        sql_int(component.get("qty") or 1),
                    ]
                )
            )
        seen_aliases = set()
        for alias in offer.get("aliases") or []:
            alias_text = str(alias).strip()
            if not alias_text or alias_text in seen_aliases:
                continue
            seen_aliases.add(alias_text)
            alias_rows.append(
                ", ".join(["'offer'", sql_str(code), sql_str(alias_text)])
            )

    emit_inserts(
        "sg_catalog_offers",
        "offer_code, name, gift_tier, page, interest_theme, interest_theme_slug, supplier_code, catalog_match_status, unboxing_experience, product_master, product_family, has_price, price_min, price_max",
        offer_rows,
        out,
        size=40,
    )
    emit_inserts(
        "sg_offer_components",
        "offer_code, product_code, qty",
        component_rows,
        out,
    )

    bundle_rows = []
    bundle_offer_rows = []
    for bundle in data.get("corporate_bundles") or []:
        code = bundle.get("bundle_code")
        name = bundle.get("name")
        bundle_rows.append(
            ", ".join(
                [
                    sql_str(code),
                    sql_str(name),
                    sql_int(bundle.get("target_recipients")),
                    sql_num(bundle.get("total_price")),
                    sql_str(bundle.get("description")),
                    sql_num(bundle.get("landed_cost")),
                    sql_num(bundle.get("gross_profit")),
                    sql_num(bundle.get("gross_margin_percent")),
                    "1" if bundle.get("meets_min_profit_threshold") else "0",
                    sql_json(bundle.get("tier_breakdown")),
                ]
            )
        )
        price_rows.append(
            ", ".join(
                [
                    sql_str(code),
                    "'bundle'",
                    sql_str(name),
                    "NULL",
                    "NULL",
                    "1",
                    sql_num(bundle.get("total_price")),
                    "'THB'",
                    sql_str("smartgift_2026"),
                ]
            )
        )
        for included in bundle.get("included_offers") or []:
            bundle_offer_rows.append(
                ", ".join(
                    [
                        sql_str(code),
                        sql_str(included.get("offer_code")),
                        sql_int(included.get("qty") or 1),
                    ]
                )
            )

    emit_inserts(
        "sg_corporate_bundles",
        "bundle_code, name, target_recipients, total_price, description, landed_cost, gross_profit, gross_margin_percent, meets_min_profit_threshold, tier_breakdown",
        bundle_rows,
        out,
        size=20,
    )
    emit_inserts(
        "sg_bundle_offers",
        "bundle_code, offer_code, qty",
        bundle_offer_rows,
        out,
    )
    emit_inserts(
        "product_prices",
        "sku, item_type, name, category_slug, gift_tier, min_qty, unit_price, currency, source",
        price_rows,
        out,
    )
    emit_inserts("sg_aliases", "item_type, sku, alias", alias_rows, out)

    sub_rows = []
    for sub in data.get("sub_catalogs") or []:
        sub_rows.append(
            ", ".join(
                [
                    sql_str(sub.get("code")),
                    sql_str(sub.get("name")),
                    sql_str(sub.get("description")),
                ]
            )
        )
    emit_inserts("sg_sub_catalogs", "code, name, description", sub_rows, out)

    out.append("""CREATE OR REPLACE VIEW v_product_price AS
SELECT
  p.code AS sku,
  'product' AS item_type,
  p.name_th AS name,
  p.category_slug,
  p.srp_price AS list_price,
  MIN(pp.unit_price) AS price_min,
  MAX(pp.unit_price) AS price_max,
  p.currency
FROM sg_products p
LEFT JOIN product_prices pp
  ON pp.sku = p.code AND pp.item_type = 'product'
GROUP BY p.code, p.name_th, p.category_slug, p.srp_price, p.currency;
""")
    out.append("SET FOREIGN_KEY_CHECKS = 1;")
    out.append("")
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--json",
        default=r"C:\Users\Admin\Downloads\1smartgift_catalog_master.json",
    )
    parser.add_argument(
        "--out",
        default=r"C:\Users\Admin\Downloads\1smartgift_catalog_master.sql",
    )
    args = parser.parse_args()
    src = Path(args.json)
    dest = Path(args.out)
    data = json.loads(src.read_text(encoding="utf-8"))
    sql = build_sql(data)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(sql, encoding="utf-8")
    print(f"Wrote {dest} ({dest.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
